-- Migration: admin_approvals
--
-- The ledger behind BRD §8.13's dual approval: "High-risk actions require
-- step-up authentication and, for selected actions, dual approval." §17 names
-- it as a mitigation for admin misuse. Its first and only action is changing an
-- account's role, which is privilege escalation and the most dangerous write an
-- administrator can make. ADR 0023.
--
-- Data impact
-- -----------
-- One new table. No existing table is touched, no backfill, no rewrite. The
-- three foreign keys point at `users`, which is why this cannot run before the
-- identity mirror exists.
--
-- Nothing deletes from this table. A refused or expired proposal is part of the
-- record of what administrators *tried* to do, which is most of the point of
-- keeping it.
--
-- `proposedById` is ON DELETE RESTRICT rather than SET NULL, unlike the audit
-- log's actor. It has to be: the column is NOT NULL, because a proposal whose
-- proposer is unknown is not evidence of anything. Accounts are soft-deleted
-- (`users.deletedAt`), so this never fires in normal operation — and if a hard
-- delete is ever attempted, failing loudly is the right outcome.
--
-- The CHECK constraints
-- --------------------
-- **The two-person rule is enforced here, not only in the service.** The same
-- reasoning as the booking overlap constraint (ADR 0004): a rule that lives
-- only in application code is a rule the next code path forgets. The cost of
-- forgetting this one is a single administrator granting themselves whatever
-- they like, so Postgres refuses it independently of anything above it.
--
-- `approver_is_not_proposer` reads as permissive but is not. A CHECK rejects
-- only FALSE, so a pending row — where `approvedById` is NULL and the
-- comparison is NULL — passes, while a self-approval is FALSE and is refused.
-- The `IS NULL OR` is written out rather than relied upon, so the pending case
-- is obvious to whoever reads this next.
--
-- The remaining three keep the row internally consistent: an approval or a
-- cancellation is all-or-nothing, and a proposal cannot be both approved and
-- cancelled. Without them a partial write leaves a row that no application
-- reading is prepared for.
--
-- Expand-and-contract
-- -------------------
-- Not applicable: a new table no previous release reads is safe in one deploy.
--
-- Application rollback: safe. Nothing in the previous release references it.
--
-- Schema rollback:
--   DROP TABLE "admin_approvals";
--   DELETE FROM _prisma_migrations WHERE migration_name LIKE '%admin_approvals';
--
-- Backup first? Not for the forward migration. The rollback discards the record
-- of every administrative approval ever granted — take one before running it
-- against a database holding rows.

-- CreateTable
CREATE TABLE "admin_approvals" (
    "id" UUID NOT NULL,
    "action" TEXT NOT NULL,
    "targetType" TEXT NOT NULL,
    "targetId" UUID NOT NULL,
    "payload" JSONB NOT NULL,
    "proposedById" UUID NOT NULL,
    "proposedReason" TEXT NOT NULL,
    "proposedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMPTZ(3) NOT NULL,
    "approvedById" UUID,
    "approvedReason" TEXT,
    "approvedAt" TIMESTAMPTZ(3),
    "cancelledById" UUID,
    "cancelledReason" TEXT,
    "cancelledAt" TIMESTAMPTZ(3),

    CONSTRAINT "admin_approvals_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "admin_approvals_proposedAt_idx" ON "admin_approvals"("proposedAt" DESC);

-- AddForeignKey
ALTER TABLE "admin_approvals" ADD CONSTRAINT "admin_approvals_proposedById_fkey" FOREIGN KEY ("proposedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "admin_approvals" ADD CONSTRAINT "admin_approvals_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "admin_approvals" ADD CONSTRAINT "admin_approvals_cancelledById_fkey" FOREIGN KEY ("cancelledById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- The dual-approval rule itself. Not generated by Prisma — added by hand, and
-- it is the reason this table exists at all.
ALTER TABLE "admin_approvals" ADD CONSTRAINT "approver_is_not_proposer"
    CHECK ("approvedById" IS NULL OR "approvedById" <> "proposedById");

-- An approval is all three columns or none of them.
ALTER TABLE "admin_approvals" ADD CONSTRAINT "approval_is_complete"
    CHECK (
        ("approvedById" IS NULL AND "approvedAt" IS NULL AND "approvedReason" IS NULL)
        OR ("approvedById" IS NOT NULL AND "approvedAt" IS NOT NULL AND "approvedReason" IS NOT NULL)
    );

-- And so is a cancellation.
ALTER TABLE "admin_approvals" ADD CONSTRAINT "cancellation_is_complete"
    CHECK (
        ("cancelledById" IS NULL AND "cancelledAt" IS NULL AND "cancelledReason" IS NULL)
        OR ("cancelledById" IS NOT NULL AND "cancelledAt" IS NOT NULL AND "cancelledReason" IS NOT NULL)
    );

-- A proposal has at most one outcome.
ALTER TABLE "admin_approvals" ADD CONSTRAINT "outcome_is_singular"
    CHECK ("approvedAt" IS NULL OR "cancelledAt" IS NULL);
