-- Migration: account_suspension
--
-- BRD §14 Phase 1 asks for account suspension; §8.1 lists it beside deletion,
-- export and blocked-user controls. §5.1 gives suspension to Trust & Safety,
-- which does not exist yet — this is the mechanism that module will eventually
-- drive, not the policy. ADR 0024.
--
-- Data impact
-- -----------
-- Three nullable columns on `users`, no defaults, so Postgres records them in
-- the catalogue without rewriting the table. Every existing row reads null,
-- which is correct: nobody is suspended.
--
-- No backfill, and nothing is destroyed. Suspension is reversible by design —
-- unlike deletion, which erases (ADR 0018) — so these columns go back to null
-- when an account is reinstated, and the audit trail is what remembers that it
-- ever happened.
--
-- The self-referencing foreign key is ON DELETE SET NULL rather than RESTRICT.
-- Losing which administrator suspended somebody is bad, but the audit trail
-- holds that permanently, and an old suspension must never be able to block
-- removing an account. The same trade `audit_logs.actorId` makes.
--
-- The CHECK constraint, and what it deliberately leaves out
-- --------------------------------------------------------
-- `suspendedAt` and `suspensionReason` are set together or not at all. A row
-- with a timestamp and no reason is one the account page cannot render
-- sensibly — it would tell somebody they are suspended and be unable to say
-- why, which is worse than either alternative.
--
-- **`suspendedById` is deliberately outside the constraint**, and the first
-- draft of this migration included it and was wrong. `ON DELETE SET NULL`
-- nulls that column when the suspending administrator is removed, which would
-- then violate an all-three-or-none CHECK and make the delete fail — turning
-- "we lost the actor" into "you cannot remove this account", the exact outcome
-- the SET NULL was chosen to avoid. The two constraints contradicted, and the
-- reasoning above says which wins: the suspension survives with an unknown
-- actor, because the audit trail holds the actor anyway.
--
-- Found by a database test, and only a database test could have found it.
--
-- Expand-and-contract
-- -------------------
-- Not applicable: nullable columns no previous release reads are safe in a
-- single deploy.
--
-- Application rollback: safe, and it **fails open**. Nothing in the previous
-- release reads these columns, so a suspended account simply becomes
-- unsuspended. Worth knowing before rolling back: if a suspension is holding
-- back an active abuser, the rollback releases them.
--
-- Schema rollback:
--   ALTER TABLE "users" DROP CONSTRAINT "suspension_is_complete";
--   ALTER TABLE "users"
--     DROP COLUMN "suspensionReason",
--     DROP COLUMN "suspendedById",
--     DROP COLUMN "suspendedAt";
--   DELETE FROM _prisma_migrations WHERE migration_name LIKE '%account_suspension';
--
-- Backup first? Not for the forward migration. The rollback discards who
-- suspended whom and why — the audit trail keeps the event, but the current
-- state is lost, so take one before running it against a database holding
-- suspensions.

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "suspendedAt" TIMESTAMPTZ(3),
ADD COLUMN     "suspendedById" UUID,
ADD COLUMN     "suspensionReason" TEXT;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_suspendedById_fkey" FOREIGN KEY ("suspendedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- A suspension always says when and why. Not generated by Prisma.
-- `suspendedById` is excluded on purpose — see the note above.
ALTER TABLE "users" ADD CONSTRAINT "suspension_is_complete"
    CHECK (
        ("suspendedAt" IS NULL AND "suspensionReason" IS NULL)
        OR ("suspendedAt" IS NOT NULL AND "suspensionReason" IS NOT NULL)
    );
